"""Generate the RWA consent resolution and vendor RFQ as PDFs (reportlab)."""
from __future__ import annotations
import io
from datetime import date
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

_ss = getSampleStyleSheet()
H = ParagraphStyle("H", parent=_ss["Title"], fontSize=17, spaceAfter=8)
B = ParagraphStyle("B", parent=_ss["BodyText"], fontSize=10.5, leading=15)
S = ParagraphStyle("S", parent=_ss["BodyText"], fontSize=8.5, textColor=colors.grey)


def _inr(n) -> str:
    return "Rs. {:,.0f}".format(n)


def _build(story) -> bytes:
    buf = io.BytesIO()
    SimpleDocTemplate(buf, pagesize=A4, leftMargin=20 * mm, rightMargin=20 * mm, topMargin=18 * mm, bottomMargin=18 * mm).build(story)
    return buf.getvalue()


def _table(rows, widths=None):
    t = Table(rows, colWidths=widths)
    t.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.4, colors.lightgrey),
                           ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
                           ("FONTSIZE", (0, 0), (-1, -1), 9.5), ("VALIGN", (0, 0), (-1, -1), "TOP")]))
    return t


def consent_resolution(case: dict, result: dict) -> bytes:
    soc = case.get("society_name", "the Society")
    kwp = result["system_kwp"]
    story = [
        Paragraph("Resolution of the General Body", H),
        Paragraph(f"{soc} &nbsp;|&nbsp; Date: {date.today():%d %B %Y}", S), Spacer(1, 8),
        Paragraph(f"<b>Subject:</b> Installation of a {kwp} kWp rooftop solar system on the common terrace of {soc}.", B), Spacer(1, 6),
        Paragraph("<b>WHEREAS</b> the Society's common-area electricity consumption is high and rooftop solar can reduce this cost "
                  "and cut emissions under the PM Surya Ghar: Muft Bijli Yojana;", B), Spacer(1, 4),
        Paragraph("<b>RESOLVED THAT</b> the General Body authorises the Managing Committee to:", B),
        Paragraph(f"1. Install a grid-connected rooftop solar system of about {kwp} kWp on the common terrace, which is declared common property of the Society for this purpose.<br/>"
                  "2. Invite quotations from MNRE-empanelled vendors and select one on the committee's recommendation.<br/>"
                  "3. Apply for subsidy and net-metering on behalf of the Society through the national portal and the local DISCOM.<br/>"
                  "4. Sign the necessary agreements, with the Secretary as authorised signatory.", B), Spacer(1, 8),
        _table([["Estimated gross cost", _inr(result["gross_cost_inr"])],
                ["Expected subsidy (to be verified)", _inr(result["subsidy_inr"])],
                ["Net cost to Society", _inr(result["net_cost_inr"])],
                ["Year-1 savings", _inr(result["year1_savings_inr"])],
                ["Estimated payback", f'{result["payback_years"]} years' if result["payback_years"] else "n/a"]],
               [70 * mm, 80 * mm]), Spacer(1, 10),
        Paragraph(f"Consent recorded: <b>{case.get('consent_pct', 0)}%</b> of members. "
                  "Passed by majority at the General Body meeting held on ____________.", B), Spacer(1, 26),
        _table([["Secretary", "Chairperson", "Treasurer"], ["\n\n\n", "\n\n\n", "\n\n\n"]], [56 * mm] * 3),
        Spacer(1, 8), Paragraph("Generated by RoofRight. Figures are estimates; subsidy amounts must be verified on the official portal.", S),
    ]
    return _build(story)


def vendor_rfq(case: dict, result: dict) -> bytes:
    soc = case.get("society_name", "the Society")
    a = result["assumptions"]
    story = [
        Paragraph("Request for Quotation: Rooftop Solar", H),
        Paragraph(f"Issued by {soc}, {case.get('city', '')} &nbsp;|&nbsp; {date.today():%d %B %Y}", S), Spacer(1, 8),
        Paragraph("Vendors are requested to submit a written quotation covering the scope below. Only MNRE-empanelled vendors are eligible for subsidy-linked work.", B), Spacer(1, 6),
        _table([["Capacity", f'{result["system_kwp"]} kWp grid-connected'],
                ["Roof area available", f'{case.get("roof_area_m2", "")} m2 (shading ~{a["shading_pct"]}%)'],
                ["Expected annual generation", f'{result["annual_generation_kwh"]:,} kWh'],
                ["Budget reference", f'{_inr(result["gross_cost_inr"])} (at {_inr(a["cost_per_kwp_inr"])}/kWp)'],
                ["Metering", "Net metering with DISCOM"],
                ["Sanctioned load", f'{case.get("sanctioned_load_kw", "n/a")} kW']], [55 * mm, 95 * mm]), Spacer(1, 8),
        Paragraph("<b>Please quote separately for:</b>", B),
        Paragraph("1. Panels (make, wattage, warranty), inverter (make, warranty), mounting structure and cabling.<br/>"
                  "2. Structural assessment and any roof reinforcement.<br/>"
                  "3. Net-meter application and DISCOM inspection support.<br/>"
                  "4. Subsidy paperwork handling.<br/>"
                  "5. Annual maintenance (5 years) and performance guarantee.<br/>"
                  "6. Payment schedule and installation timeline.", B), Spacer(1, 8),
        _table([["Vendor", "Capacity", "Price (Rs.)", "Warranty", "Timeline"]] + [["", "", "", "", ""]] * 3),
        Spacer(1, 8), Paragraph("Generated by RoofRight.", S),
    ]
    return _build(story)
